server:
  # 服务器端口号
  port: 9000
  servlet:
    context-path: /api
spring:
  #由于Spring Boot 2.6.x 请求路径与 Spring MVC 处理映射匹配的默认策略从AntPathMatcher更改为PathPatternParser。所以需要设置spring.mvc.pathmatch.matching-strategy为ant-path-matcher来改变它。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    # 选择环境
    active: @activatedProperties@
  # 配置数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      connect-timeout: 30000
      test-while-idle: true
      #web模块
      web-stat-filter:
        enabled: true
        url-pattern: /*
      #监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
      # 监控过滤器配置
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          enabled: true
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
  ## 数据库版本管理
  flyway:
    # 是否启用，默认为true
    enabled: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
    # 第一次运行时会执行所有脚本，当删除flyway_schema_history表后，会跳过20230831006和之前的脚本
    baseline-version: 20230831006
  #jpa配置
  jpa:
    #打印日志
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  # redis 配置
  redis:
    # 连接超时时间
    timeout: 10s
    #自 Spring Boot 2.2 版本起，Lettuce 取代了之前的默认客户端 Jedis，成为 Spring Boot 中与 Redis 进行交互的首选客户端。
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#日志配置
logging:
  config: classpath:logback-spring.xml #使用logback进行配置

# knife4j
knife4j:
  enable: true

# 放行的url
security:
  ignore:
    urls:
      - /user/login
      - /swagger-ui.html
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs
      - /webjars/**
      - /druid/**
      - /favicon.ico

