spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/java_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  ### 配置Redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root